import { ApiClient } from '../api/api-client.js?v=phase4-1';
import { ApiError, NetworkError, RequestTimeoutError } from '../api/api-errors.js';
import { AuthState } from './auth-state.js';
import { ApiAuthAdapter } from './api-auth-adapter.js';

export class AuthService {
  constructor(config, { fetchImpl = globalThis.fetch, legacyHooks = {} } = {}) { this.config = config; this.state = new AuthState(config.authMode); this.client = new ApiClient({ baseUrl: config.apiBaseUrl, timeoutMs: config.requestTimeoutMs, fetchImpl }); this.legacyHooks = legacyHooks; this.adapter = null; this.client.setAuthenticationFailureHandler(() => this.expireSession()); }
  async initialize() {
    if (this.config.authMode === 'legacy-demo') { const { LegacyDemoAuthAdapter } = await import('./legacy-demo-auth-adapter.js'); this.adapter = new LegacyDemoAuthAdapter(this.legacyHooks); this.state.guest(); return this.state.snapshot; }
    this.adapter = new ApiAuthAdapter(this.client); this.client.setRefreshHandler(async () => { const refreshed = await this.adapter.refreshSession(); this.acceptTokens(refreshed); return refreshed; });
    try { const restored = await this.adapter.restoreSession(); this.acceptTokens(restored); return await this.completeAuthentication(restored); }
    catch (error) { if (error instanceof ApiError && error.status === 401) return this.state.guest(); const safe = this.safeError(error); const diagnostic = this.config.environment === 'development' && error?.cause?.message ? ` ${error.cause.message}` : ''; console.warn(`[CeylonSwift] Session bootstrap unavailable (${safe.code})${safe.requestId ? ` request ${safe.requestId}` : ''}.${diagnostic}`); return this.state.guest(error instanceof NetworkError || error instanceof RequestTimeoutError ? 'unavailable' : 'guest', safe); }
  }
  async login(credentials) { const result = await this.adapter.login(credentials); if (this.config.authMode === 'legacy-demo') return this.state.authenticated({ user: result.user, session: result.session, activeWorkspace: result.legacyRole ? { roles: [result.legacyRole] } : null }); this.acceptTokens(result); return this.completeAuthentication(result); }
  async completeAuthentication(result) { const workspaceResult = await this.adapter.getWorkspaces(); const workspaces = workspaceResult.workspaces ?? []; let activeWorkspace = result.workspace ?? this.restoredWorkspace(workspaces, result.session?.workspace); if (!activeWorkspace && workspaces.length === 1 && this.config.enableWorkspaceSelector) { const selected = await this.adapter.selectWorkspace(workspaces[0].id); this.acceptTokens(selected); activeWorkspace = selected.workspace; } const capability = await this.loadCapabilities(activeWorkspace); return this.state.authenticated({ user: result.user, session: result.session, accessToken: this.client.getAccessToken(), workspaces, activeWorkspace, ...capability }); }
  async selectWorkspace(workspaceId) { const result = await this.adapter.selectWorkspace(workspaceId); this.acceptTokens(result); const [current, capability] = await Promise.all([this.adapter.getCurrentUser(), this.loadCapabilities(result.workspace)]); return this.state.authenticated({ user: current.user, session: current.session, accessToken: this.client.getAccessToken(), activeWorkspace: result.workspace, ...capability }); }
  requestOtp(payload) { return this.adapter.requestOtp(payload); }
  verifyOtp(payload) { return this.adapter.verifyOtp(payload); }
  startGoogleLogin() { return this.adapter.startGoogleLogin(); }
  async request(path, options = {}) { return (await this.client.request(path, { ...options, authenticated: options.authenticated !== false })).data; }
  async logout(allDevices = false) { let warning = null; try { await (allDevices ? this.adapter.logoutAll() : this.adapter.logout()); } catch (error) { warning = this.safeError(error); } finally { this.client.setAccessToken(null); this.state.guest(); } return { warning }; }
  expireSession() { this.client.setAccessToken(null); this.state.guest('sessionExpired', { message: 'Your session has expired. Please sign in again.' }); }
  acceptTokens(result) { if (result?.accessToken) this.client.setAccessToken(result.accessToken); }
  restoredWorkspace(workspaces, selected) { if (!selected) return null; if (selected.membershipId) return workspaces.find(workspace => workspace.id === selected.membershipId) ?? null; if (!selected.organizationId && !selected.branchId) return workspaces.find(workspace => workspace.type === 'PERSONAL') ?? null; return null; }
  async loadCapabilities(activeWorkspace) { if (!activeWorkspace || this.config.authMode !== 'api') return { capabilities: null, capabilityStatus: 'idle', capabilityError: null }; try { return { capabilities: await this.adapter.getCapabilities(), capabilityStatus: 'ready', capabilityError: null }; } catch (error) { return { capabilities: null, capabilityStatus: 'unavailable', capabilityError: this.safeError(error) }; } }
  safeError(error) { return { code: error?.code ?? 'REQUEST_FAILED', message: this.messageFor(error), requestId: error?.requestId ?? null }; }
  messageFor(error) { const messages = { AUTH_INVALID_CREDENTIALS: 'Unable to complete authentication.', AUTH_SESSION_INVALID: 'Your session has expired. Please sign in again.', AUTH_RATE_LIMITED: 'Too many attempts. Please wait and try again.', AUTH_OTP_INVALID: 'The verification code is invalid or expired.', AUTH_PROVIDER_UNAVAILABLE: 'Google authentication is currently unavailable.', AUTH_WORKSPACE_INVALID: 'This workspace is no longer available.', AUTH_PERMISSION_DENIED: 'You are not authorized to use this workspace action.', AUTH_STEP_UP_REQUIRED: 'Additional verification is required to continue.', NETWORK_ERROR: 'The authentication service is unavailable. The public site is still available.', REQUEST_TIMEOUT: 'The request timed out. Please try again.' }; return messages[error?.code] ?? error?.message ?? 'Unable to complete the request.'; }
}
