import test from 'node:test';
import assert from 'node:assert/strict';
import { AuthState } from '../../js/auth/auth-state.js';
import { ApiAuthAdapter } from '../../js/auth/api-auth-adapter.js';
import { AuthService } from '../../js/auth/auth-service.js';
import { loadRuntimeConfig } from '../../js/config/runtime-config.js';
import { mapLegacyRole } from '../../js/compatibility/legacy-role-map.js';

test('auth state transitions and logout cleanup keep tokens and capabilities in memory only', () => { const state = new AuthState('api'); assert.equal(state.snapshot.status, 'initializing'); state.authenticated({ user: { id: 'u' }, accessToken: 'token', workspaces: [{ id: 'w' }], capabilities: { workspace: { type: 'PERSONAL' }, roles: ['CUSTOMER'], permissions: ['package.create'] }, capabilityStatus: 'ready' }); assert.equal(state.snapshot.status, 'authenticated'); state.guest('sessionExpired'); assert.deepEqual(state.snapshot, { status: 'sessionExpired', user: null, accessToken: null, session: null, workspaces: [], activeWorkspace: null, capabilities: null, capabilityStatus: 'idle', capabilityError: null, authenticationMode: 'api', lastError: null }); });
test('API login sends no selected role or permissions', async () => { let request; const adapter = new ApiAuthAdapter({ request: async (path, options) => { request = { path, options }; return { data: {} }; } }); await adapter.login({ identifier: 'owner@example.test', password: 'password', selectedUiRole: 'Owner' }); assert.deepEqual(request.options.body, { identifier: 'owner@example.test', password: 'password', clientType: 'WEB', deviceName: 'CeylonSwift Web' }); });
test('production forces API mode and disables legacy demo auth', () => { const original = console.error; console.error = () => {}; try { const config = loadRuntimeConfig({ environment: 'production', authMode: 'legacy-demo', enableLegacyDemoAuth: true }); assert.equal(config.authMode, 'api'); assert.equal(config.enableLegacyDemoAuth, false); } finally { console.error = original; } });
test('legacy role mapping is navigation-only and safely restricts partner roles', () => { assert.equal(mapLegacyRole(['CUSTOMER']), 'Customer'); assert.equal(mapLegacyRole(['RIDER']), 'Rider'); assert.equal(mapLegacyRole(['OFFICE_STAFF']), 'Office'); assert.equal(mapLegacyRole(['ADMIN']), 'Owner'); assert.equal(mapLegacyRole(['PARTNER_ADMIN']), null); });
test('localStorage and UI role manipulation cannot restore an API session', async () => { globalThis.localStorage = { getItem: () => JSON.stringify({ activeRole: 'Owner', accessToken: 'forged' }) }; const config = loadRuntimeConfig({ environment: 'development', authMode: 'api', enableLegacyDemoAuth: false, apiBaseUrl: 'http://api.test' }); const service = new AuthService(config, { fetchImpl: async () => new Response(JSON.stringify({ success: false, error: { code: 'AUTH_SESSION_INVALID', message: 'Authentication is required.' } }), { status: 401 }) }); const state = await service.initialize(); assert.equal(state.status, 'guest'); assert.equal(state.accessToken, null); delete globalThis.localStorage; });
test('old Owner credentials receive no special treatment in API mode', async () => { let sent; const config = loadRuntimeConfig({ environment: 'development', authMode: 'api', enableLegacyDemoAuth: false, apiBaseUrl: 'http://api.test' }); const service = new AuthService(config, { fetchImpl: async (_url, options) => { sent = JSON.parse(options.body); return new Response(JSON.stringify({ success: false, error: { code: 'AUTH_INVALID_CREDENTIALS', message: 'Unable to complete authentication.' } }), { status: 401 }); } }); await service.initialize(); await assert.rejects(service.login({ identifier: 'prabothweerawansha@gmail.com', password: 'admin123', selectedUiRole: 'Owner' })); assert.equal(sent.identifier, 'prabothweerawansha@gmail.com'); assert.equal('selectedUiRole' in sent, false); });
test('OTP requests use backend challenges and never generate browser codes', async () => { let request; const adapter = new ApiAuthAdapter({ request: async (path, options) => { request = { path, options }; return { data: { challengeId: 'challenge', resendAfter: 60 } }; } }); const result = await adapter.requestOtp({ identifier: 'user@example.test', channel: 'EMAIL' }); assert.equal(result.challengeId, 'challenge'); assert.deepEqual(request, { path: '/auth/otp/request', options: { method: 'POST', body: { identifier: 'user@example.test', channel: 'EMAIL', purpose: 'LOGIN' } } }); assert.equal('code' in request.options.body, false); });
test('valid API login loads one workspace and its backend capabilities', async () => { const calls = []; const envelope = data => new Response(JSON.stringify({ success: true, data, requestId: 'r' }), { status: 200 }); const fetchImpl = async (url, options) => { calls.push({ url, options }); if (url.endsWith('/auth/refresh')) return new Response(JSON.stringify({ success: false, error: { code: 'AUTH_SESSION_INVALID', message: 'Authentication is required.' } }), { status: 401 }); if (url.endsWith('/auth/login')) return envelope({ accessToken: 'login-token', user: { id: 'u' }, session: { id: 's', workspace: { membershipId: null, organizationId: null, branchId: null } } }); if (url.endsWith('/auth/workspaces')) return envelope({ workspaces: [{ id: 'w', type: 'ORGANIZATION', displayName: 'Workspace', roles: ['OFFICE_STAFF'] }] }); if (url.endsWith('/auth/workspaces/select')) return envelope({ accessToken: 'workspace-token', workspace: { type: 'ORGANIZATION', membershipId: 'w', roles: ['OFFICE_STAFF'] } }); if (url.endsWith('/auth/capabilities')) return envelope({ workspace: { type: 'ORGANIZATION', membershipId: 'w' }, roles: ['OFFICE_STAFF'], permissions: ['package.read.branch'] }); if (url.endsWith('/auth/me')) return envelope({ user: { id: 'u' }, session: { id: 's' } }); throw new Error('Unexpected request'); }; const service = new AuthService(loadRuntimeConfig({ apiBaseUrl: 'http://api.test', authMode: 'api' }), { fetchImpl }); await service.initialize(); const result = await service.login({ identifier: 'user@example.test', password: 'strong-password' }); assert.equal(result.status, 'authenticated'); assert.equal(result.accessToken, 'workspace-token'); assert.equal(result.activeWorkspace.membershipId, 'w'); assert.equal(result.capabilityStatus, 'ready'); assert.deepEqual(result.capabilities.permissions, ['package.read.branch']); assert.equal(calls.some(call => call.url.endsWith('/auth/capabilities')), true); });
test('logout clears local authentication even when server confirmation fails', async () => { const service = new AuthService(loadRuntimeConfig({ apiBaseUrl: 'http://api.test', authMode: 'api' }), { fetchImpl: async () => { throw new TypeError('offline'); } }); service.adapter = { logout: async () => { throw new TypeError('offline'); } }; service.client.setAccessToken('memory-token'); service.state.authenticated({ user: { id: 'u' }, accessToken: 'memory-token', workspaces: [{ id: 'w' }] }); const result = await service.logout(); assert.equal(service.state.snapshot.status, 'guest'); assert.equal(service.client.getAccessToken(), null); assert.ok(result.warning); });
